baseurl = "https://wuzhenhuan428.github.io"
languageCode = "zh-cn"
title = "WuZhenhuan428's Blog"

defaultContentLanguage = "zh-cn"

hasCJKLanguage = true

disqusShortname = "WuZhenhuan428"

[pagination]
pagerSize = 5